export const FETCH_STAR_WARS_ENTITIES = "FETCH_STAR_WARS_ENTITIES";
export const CREATE_CHARACTER = "CREATE_CHARACTER";
export const UPDATE_CHARACTER = "UPDATE_CHARACTER";
export const REMOVE_CHARACTER = "REMOVE_CHARACTER";
