export const GET_CATEGORIES = "GET_CATEGORIES";
export const IS_CATEGORIES_LOADING = "IS_CATEGORIES_LOADING";
export const GET_SELECTED_CATEGORY = "GET_SELECTED_CATEGORY";
export const IS_ALL_ENTITIES_EMPTY = "IS_ALL_ENTITIES_EMPTY";
export const GET_CATEGORY_DATA = "GET_CATEGORY_DATA";
export const GET_SELECTED_CHARACTER = "GET_SELECTED_CHARACTER";
